### ISSUE TITLE
Kleine Beschreibung für die Einsatzstärken

### ISSUE THREAD

**Issue by Lling** [goerdy/FuehrungsstellenStatusMonitor#1]
Könnte man noch ein kleines Feld als Überschrifften für die Einsatzstärken hinzufügen?
So könnte man sich individuelle Möglichkeiten schaffen, wie viel Atemschutzgeräteträger bspw. vorhanden sind etc.
Je nach Einsatz wären ja andere Werte interessanter in der Übersicht.

**Comment by goerdy** [comment]
Hey, meinst du alternativ zur normalen Stärke oder zusätzlich?
Wie viele Felder hättest du den gerne?
Ich würde erst Mal sagen 3 zusätzliche Felder sollten reichen oder?

**Comment by Lling** [comment]
![monitor](https://github.com/goerdy/FuehrungsstellenStatusMonitor/assets/6634017/17fac0b5-0efa-4e4e-ac5d-2133f5b5926d)
Ich meinte jetzt für die Zahlen. Damit man weiß, wofür die einzelnen Felder stehen. Bzw das man diese vielleicht individuell verwenden könnte.

**Comment by goerdy** [comment]
Ja, habe ich verstanden. Ich würde aber die eigentliche Stärke der Einheiten auf jeden Fall beibehalten und zusätzliche, frei benennbare Felder hinzufügen. Also dann für z.B. "AGT" "CE" "Sani"....

Da ist jetzt die Frage wie viele solcher freien Felder du für sinnvoll hälst.

**Comment by Lling** [comment]
Ich glaub maximal 3 sollten reichen. 
Mehr unterschiedliche Leute wird man auf nem Fahrzeug auch nicht haben.

**Comment by goerdy** [comment]
Hab das feature eingebaut. teste Mal bitte ob das so für dich passt

**Comment by Lling** [comment]
Sieht top aus! Besten Dank

**Comment by goerdy** [comment]
Jau gerne, dann mach ich die Issue zu.

Darf ich fragen wo und wie du den Statusmonitor einsetzt?

**Comment by Lling** [comment]
Ich überlege den für Übungen bzw. auf Einsatzfahrten auf dem Tablet im Fahrzeug zu nutzen um so direkt den Einsatz im Anschluss auswerten zu können bzw. alles als Übersicht zu haben.
